Automation: If ACS consent is missing, skip events and submissions. There may be a race condition where the service itself is stopping due to missing consent, but we still get an event causing:
```

kotlin.UninitializedPropertyAccessException: lateinit property serviceScope has not been initialized
	at eu.darken.sdmse.automation.core.AutomationService.onAccessibilityEvent(AutomationService.kt:139)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2081)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2284)
```